title: 5LV10's Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A minimal, modern blog built with Jekyll.
baseurl: "/articles" 
url: "" 

github_username: gouthamk16

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
future: true
